//@version=3
strategy(title="CCI Scalper", shorttitle="CCI Scalper", overlay=false, default_qty_value=1, backtest_fill_limits_assumption=1, calc_on_every_tick=true)

FastMA = input(10, minval=1)
SlowMA = input(20, minval=1)
upperBoundLine = input(200.000, "CCI Upper line", type=float)
lowerBoundLine = input(-200.000, "CCI Lower line", type=float)
useSMA = input(false, "Use SMA with CCI", type=bool)
trailPoints = input(140, "Trail Points (in ticks)", type=integer)
trailOffset = input(100, "Trail Offset (in ticks)", type=integer)
testType = input('Trail Points', "Test Points or Price", options=['Trail Points', 'Trail Price'])


// === INPUT BACKTEST RANGE ===
FromDay   = input(defval = 14, title = "From Day", minval = 1, maxval = 31)
FromMonth = input(defval = 11, title = "From Month", minval = 1, maxval = 12)
FromYear  = input(defval = 2018, title = "From Year", minval = 2017)
ToDay     = input(defval = 1, title = "To Day", minval = 1, maxval = 31)
ToMonth   = input(defval = 1, title = "To Month", minval = 1, maxval = 12)
ToYear    = input(defval = 9999, title = "To Year", minval = 2017)
start     = timestamp(FromYear, FromMonth, FromDay, 00, 00)  // backtest start window
finish    = timestamp(ToYear, ToMonth, ToDay, 23, 59)        // backtest finish window
window()  => time >= start and time <= finish ? true : false // create function "within window of time"

hline(upperBoundLine, color=gray, linestyle=dashed)
//hline(0, color=purple, linestyle=dashed)
hline(lowerBoundLine, color=gray, linestyle=dashed)

xCCI = cci(close, 10)
xSMA = sma(xCCI, SlowMA)
xFMA = sma(xCCI, FastMA)
pos = 0
pos := iff(xSMA < xFMA , 1, iff(xSMA > xFMA, -1, nz(pos[1], 0)))

isSellSignal = useSMA ? crossunder(xSMA, xFMA) : crossunder(xCCI, upperBoundLine) 
isBuySignal = useSMA ? crossover(xSMA, xFMA) : crossover(xCCI, lowerBoundLine)

// Visualise the Opening positions
plotshape(isSellSignal ? 1 : na, style=shape.arrowdown, location=location.absolute, color=green, text="Sell")
plotshape(isBuySignal ? 1 : na, style=shape.arrowup, location=location.absolute, color=red, text="Buy")

// barcolor(pos == -1 ? red: pos == 1 ? green : blue)
plot(xSMA, color=red, title="CCI MA Slow")
plot(xFMA, color=blue, title="CCI MA FAST")
// plot(xCCI, color=(isSellSignal or isBuySignal) ? red : green, title="CCI Standard")
plot(xCCI, color=(xCCI > upperBoundLine or xCCI < lowerBoundLine) ? red : green, title="CCI Standard")

if (isBuySignal)
    strategy.close("sell")
    strategy.order("buy", strategy.long, 1, comment="buy", when=window())
    strategy.exit("Trailing Stop (buy)", "buy", trail_points= trailPoints, trail_offset= trailOffset, when= testType == 'Trail Points' and window())


if (isSellSignal)
    strategy.close("buy")
    strategy.order("sell", strategy.short, 1, comment="sell", when=window())
    strategy.exit("Trailing Stop (sell)", "sell", trail_points= trailPoints, trail_offset= trailOffset, when= testType == 'Trail Points' and window())
