//@version=3
study(title="Pleo_Ross Ichimoku Cloud", shorttitle="Pleo", overlay=true)

conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")

donchian(len) => avg(lowest(len), highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

plot(conversionLine, color=blue, title="Conversion Line")
plot(baseLine, color=purple, title="Base Line")
plot(close, offset = -displacement, color=#459915, title="Lagging Span")

p1 = plot(leadLine1, offset = displacement, color=green,
 title="Lead 1")
p2 = plot(leadLine2, offset = displacement, color=red, 
 title="Lead 2")
fill(p1, p2, color = leadLine1 > leadLine2 ? green : red)

// find where the lines cross
c = cross(conversionLine, baseLine)

//create the alert condition
alertcondition(c, title='conversionLine crosses baseLine', message='baseLine and conversionLine have crossed!')

//logic for seeing the trend
upTrend = (close > conversionLine and close > baseLine)
plotshape(c, style=shape.flag, location=location.abovebar, color=upTrend ? green : red)
