//@version=3
study(title="Pleo_Ross Ichimoku Only Alert Integration V7", shorttitle="PleoIchV7Alert", overlay=true)

//Ichimoku input Logic
conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")
candlePeriod = input(title="Candlestick Period", defval='45', options=['1', '3', '5', '10', '15', '30', '45', '60', '120', '180', '240', 'D', 'W', 'M'])

//Ichimoku function Logic
donchian(len) => avg(lowest(len), highest(len))

//Ichimoku line Logic
tenkanLine = donchian(conversionPeriods)
kijunLine = donchian(basePeriods)
leadLine1 = avg(tenkanLine, kijunLine)
leadLine2 = donchian(laggingSpan2Periods)

// Plot Ichimoku Cloud
plot(tenkanLine, color=blue, linewidth=3, title="Tenkan Line")
plot(kijunLine, color=red, linewidth=3, title="Kijun Line")
plot(close, offset = -displacement, color=yellow, linewidth=2, title="Chikou Lagging Span")
p1 = plot(leadLine1, offset = displacement, color=white, title="Lead 1")
p2 = plot(leadLine2, offset = displacement, color=white, title="Lead 2")
fill(p1, p2, color = leadLine1 > leadLine2 ? green : red)

// Logic for open positions
isBuySignal = crossover(tenkanLine, kijunLine) 
isSellSignal = crossunder(tenkanLine, kijunLine) 

// Visualise the Opening positions
plotshape(isBuySignal, style=shape.arrowup, location=location.abovebar, color=green, size=size.large, text="Buy")
plotshape(isSellSignal, style=shape.arrowdown, location=location.belowbar, color=red, size=size.large, text="Sell")

//Alert conditions
alertcondition(isBuySignal, title='Buy', message='Buy signal')
alertcondition(isSellSignal, title='Sell', message='Sell signal')
