//@version=3
study(title="Pleo_Ross Ichimoku Cloud", shorttitle="Pleo", overlay=true)

//Ichimoku input Logic
conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")

//Ichimoku function Logic
donchian(len) => avg(lowest(len), highest(len))

//Ichimoku line Logic
conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

// previous values persistence
previousTenkan = 0.0
previousTenkan := nz(conversionLine[1])
previousKijun = 0.0
previousKijun := nz(baseLine[1])

// find where the lines cross
c = cross(conversionLine, baseLine)

//logic for seeing the trend
isBlueUp = previousTenkan < previousKijun

// plot visuals
plot(conversionLine, color=blue, linewidth=3, title="Tenkan Line")
plot(baseLine, color=red, linewidth=3, title="Kijun Line")
plot(close, offset = -displacement, color=green, linewidth=2, title="Chikou Lagging Span")

p1 = plot(leadLine1, offset = displacement, color=white,
 title="Lead 1")
p2 = plot(leadLine2, offset = displacement, color=white, 
 title="Lead 2")
fill(p1, p2, color = leadLine1 > leadLine2 ? green : red)

plotshape(c, style=shape.flag, location=location.abovebar, color=isBlueUp ? green : red)

//create the alert condition
alertcondition(c, title='conversionLine crosses baseLine', message='baseLine and conversionLine have crossed!')


